package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.example.jdbcdemo.domain.Instrument;

public class InstrumentManagerImpl implements InstrumentManager{
	
	private Connection conn;
	
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";

	private String createTable = "CREATE TABLE instrument(id bigint GENERATED BY DEFAULT AS IDENTITY, brand varchar(20), name varchar(20), price decimal(8,2))";

	private Statement statement;
	
	public InstrumentManagerImpl(){
		connect();
	}
	
	private void connect(){
		try {
			conn = DriverManager.getConnection(url);
			statement = conn.createStatement();

			ResultSet rs = conn.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("instrument".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTable);

//			addPersonStmt = connection
//					.prepareStatement("INSERT INTO Person (name, yob) VALUES (?, ?)");
//			deleteAllPersonsStmt = connection
//					.prepareStatement("DELETE FROM Person");
//			getAllPersonsStmt = connection
//					.prepareStatement("SELECT id, name, yob FROM Person");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	@Override
	public int addInstrument(Instrument inst) {
		int count = 0;
		try{		
			String query = "insert into instrument (brand, name, price) values (?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, inst.getBrand());
            stmt.setString(2, inst.getName());
            stmt.setDouble(3, inst.getPrice());
            
            count = stmt.executeUpdate(query);
            
            
		} catch(SQLException e){
			e.printStackTrace();
		}
		return count;
}

	@Override
	public void deleteInstrument(long id) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public List<Instrument> getInstrument() {
		List<Instrument> instruments = new ArrayList<>();
		try{		
			String query = "select * from instrument;";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            
            while(rs.next()){
            	long id = rs.getLong("id");
            	String brand = rs.getString("brand");
            	String name = rs.getString("name");
            	double price = rs.getDouble("price");
            	
            	instruments.add(new Instrument(id, brand, name, price));
            }
            
		} catch(SQLException e){
			e.printStackTrace();
		}
		return instruments;
	}

	@Override
	public Instrument updateInstrument(long id) {
		// TODO Auto-generated method stub
		return null;
	}
	
	Connection getConnection() {
		return conn;
	}
	
	
}
