package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.example.jdbcdemo.domain.Instrument;

public class InstrumentManagerImpl implements InstrumentManager{
	
	private Connection conn;
	
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";

	private String createTable = "CREATE TABLE instrument(id bigint GENERATED BY DEFAULT AS IDENTITY, brand varchar(20), name varchar(20) NOT NULL, price decimal(8,2))";

	private Statement statement;
	
	public InstrumentManagerImpl(){
		connect();
	}
	
	private void connect(){
		try {
			conn = DriverManager.getConnection(url);
			statement = conn.createStatement();

			ResultSet rs = conn.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("instrument".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTable);

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	void clearInstruments() {
		try {
			PreparedStatement stmt = conn.prepareStatement("delete from instrument");
			stmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	@Override
	public int addInstrument(Instrument inst) {
		int count = 0;
		try{
			conn.setAutoCommit(false);
			String query = "insert into instrument (brand, name, price) values (?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, inst.getBrand());
            stmt.setString(2, inst.getName());
            stmt.setDouble(3, inst.getPrice());
            
            count = stmt.executeUpdate();
            
            
		} catch(SQLException e){
			e.printStackTrace();
		}
		return count;
	}

	@Override
	public int addAllInstrument(ArrayList<Instrument> inst){

		int count = 0;
		try{
			conn.setAutoCommit(false);

			for(Instrument instrument : inst){
				String query = "insert into instrument (brand, name, price) values (?, ?, ?)";
				PreparedStatement stmt = conn.prepareStatement(query);
				stmt.setString(1, instrument.getBrand());
				stmt.setString(2, instrument.getName());
				stmt.setDouble(3, instrument.getPrice());

				count += stmt.executeUpdate();
			}
			conn.commit();

		}catch (SQLException e){
			try{
				conn.rollback();

			} catch (SQLException x){
				x.printStackTrace();
			}
		}

		return count;
	}

	@Override
	public int deleteInstrument(long id) {
		int count = 0;
		String query = "delete from instrument where id = ?";
		try{
			PreparedStatement stmt = conn.prepareStatement(query);
			stmt.setInt(1, (int)id);
			count = stmt.executeUpdate();

		} catch (SQLException e){
			e.printStackTrace();
			return 0;
		}
		return count;
	}

	@Override
	public int deleteAllInstruments(ArrayList<Instrument> inst){

		int count = 0;
		try{
			conn.setAutoCommit(false);

			for(Instrument instrument : inst){
				String query = "delete from instrument where id = ?";
				PreparedStatement stmt = conn.prepareStatement(query);
				stmt.setLong(1, instrument.getId());

				count += stmt.executeUpdate();
			}
			conn.commit();

		}catch (SQLException e){
			try{
				conn.rollback();

			} catch (SQLException x){
				x.printStackTrace();
			}
		}

		return count;
	}

	@Override
	public Instrument getInstrument(String name) {
		Instrument inst = new Instrument();

		try{
			String query = "select * from instrument where name = ?";
			PreparedStatement stmt = conn.prepareStatement(query);
			stmt.setString(1, name);
			ResultSet rs = stmt.executeQuery();

			while(rs.next()){
				inst.setId(rs.getLong("id"));
				inst.setBrand(rs.getString("brand"));
				inst.setName(rs.getString("name"));
				inst.setPrice(rs.getDouble("price"));
			}

		} catch(SQLException e){
			e.printStackTrace();
		}
		return inst;
	}

	@Override
	public List<Instrument> getAllInstrument() {
		List<Instrument> instruments = new ArrayList<>();
		try{		
			String query = "select * from instrument;";
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();
            
            while(rs.next()){
            	long id = rs.getLong("id");
            	String brand = rs.getString("brand");
            	String name = rs.getString("name");
            	double price = rs.getDouble("price");
            	
            	instruments.add(new Instrument(id, brand, name, price));
            }
            
		} catch(SQLException e){
			e.printStackTrace();
		}
		return instruments;
	}

	@Override
	public int updateInstrument(Instrument inst) {
		int count = 0;
		try{
			String query = "update instrument set brand = ?, name = ?, price = ? where id = ?";

			PreparedStatement stmt = conn.prepareStatement(query);
			stmt.setString(1, inst.getBrand());
			stmt.setString(2, inst.getName());
			stmt.setDouble(3, inst.getPrice());
			stmt.setLong(4, inst.getId());
            count = stmt.executeUpdate();
		} catch (SQLException e){
			e.printStackTrace();
			return 0;
		}
		return count;
	}

//	@Override
//	public void addUpdateDelete(ArrayList<Instrument> inst){
//		try {
//
//		} catch (SQLException e){
//			try {
//
//			}catch (SQLException ex){
//				ex.printStackTrace();
//			}
//		}
//	}
//
	Connection getConnection() {
		return conn;
	}
	
	
}
